version: "3.3"

services:

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    hostname: grafana
    image: grafana/grafana
    ports:
      - "3000:3000"

  app1:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - prometheus
    ports:
      - "5001:5000"
  app2:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - prometheus
    ports:
      - "5002:5000"
    
  nginx:
    build: /nginx
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - app1
      - app2

