"""initial migration

Revision ID: 8c084f609fb4
Revises: 
Create Date: 2023-05-21 15:25:54.418162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c084f609fb4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doctorTime',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doctor', sa.String(length=50), nullable=False),
    sa.Column('patient', sa.String(length=50), nullable=False),
    sa.Column('date', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('doctorTime')
    # ### end Alembic commands ###
